//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OneTSQ.WebServiceUtility.CallWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FuncWebServiceProcessSoap", Namespace="http://tempuri.org/")]
    public partial class FuncWebServiceProcess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckWsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessComandOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FuncWebServiceProcess() {
            this.Url = global::OneTSQ.WebServiceUtility.Properties.Settings.Default.OneTSQ_WebServiceUtility_CallWs_FuncWebServiceProcess;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckWsCompletedEventHandler CheckWsCompleted;
        
        /// <remarks/>
        public event ProcessComandCompletedEventHandler ProcessComandCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckWs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckWs() {
            object[] results = this.Invoke("CheckWs", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckWsAsync() {
            this.CheckWsAsync(null);
        }
        
        /// <remarks/>
        public void CheckWsAsync(object userState) {
            if ((this.CheckWsOperationCompleted == null)) {
                this.CheckWsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckWsOperationCompleted);
            }
            this.InvokeAsync("CheckWs", new object[0], this.CheckWsOperationCompleted, userState);
        }
        
        private void OnCheckWsOperationCompleted(object arg) {
            if ((this.CheckWsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckWsCompleted(this, new CheckWsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessComand", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AjaxOut ProcessComand(string SecurityCode, string XmlData, string XmlDataSchema) {
            object[] results = this.Invoke("ProcessComand", new object[] {
                        SecurityCode,
                        XmlData,
                        XmlDataSchema});
            return ((AjaxOut)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessComandAsync(string SecurityCode, string XmlData, string XmlDataSchema) {
            this.ProcessComandAsync(SecurityCode, XmlData, XmlDataSchema, null);
        }
        
        /// <remarks/>
        public void ProcessComandAsync(string SecurityCode, string XmlData, string XmlDataSchema, object userState) {
            if ((this.ProcessComandOperationCompleted == null)) {
                this.ProcessComandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessComandOperationCompleted);
            }
            this.InvokeAsync("ProcessComand", new object[] {
                        SecurityCode,
                        XmlData,
                        XmlDataSchema}, this.ProcessComandOperationCompleted, userState);
        }
        
        private void OnProcessComandOperationCompleted(object arg) {
            if ((this.ProcessComandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessComandCompleted(this, new ProcessComandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AjaxOut {
        
        private string infoMessageField;
        
        private string htmlContentField;
        
        private string refKeyIdField;
        
        private object retObjectField;
        
        private object retObject1Field;
        
        private object retObject2Field;
        
        private object retObject3Field;
        
        private object retObject4Field;
        
        private object retObject5Field;
        
        private object retObjectExtraParam1Field;
        
        private object retObjectExtraParam2Field;
        
        private object retObjectExtraParam3Field;
        
        private object retObjectExtraParam4Field;
        
        private object retObjectExtraParam5Field;
        
        private string retUrlField;
        
        private string retUrlTargetField;
        
        private string retExtraParam1Field;
        
        private string retExtraParam2Field;
        
        private string retExtraParam3Field;
        
        private string retExtraParam4Field;
        
        private string retExtraParam5Field;
        
        private string retExtraParam6Field;
        
        private string saveFileField;
        
        private bool errorField;
        
        private bool retBooleanField;
        
        private int retNumberField;
        
        private int retNumber1Field;
        
        private int retNumber2Field;
        
        private int retNumber3Field;
        
        private int retNumber4Field;
        
        private decimal retNumberDecimalField;
        
        private decimal retNumberDecimal1Field;
        
        private decimal retNumberDecimal2Field;
        
        private decimal retNumberDecimal3Field;
        
        private decimal retNumberDecimal4Field;
        
        private decimal retDecimalField;
        
        private bool isReturnUrlLinkField;
        
        private string xmlDataField;
        
        private string xmlDataSchemaField;
        
        private byte[] retBytesField;
        
        private byte[] mediaBytesField;
        
        private string focusControlField;
        
        private string xmlDataResultField;
        
        private string xmlDataResultSchemaField;
        
        private bool showDialogMessageField;
        
        private string processServiceIdField;
        
        private string assetCodeField;
        
        private string assetLevelIdField;
        
        private string followUpSubjectField;
        
        private string followUpDescriptionField;
        
        private string ownerIdField;
        
        private string followUpStatusField;
        
        private string quickHelpField;
        
        private int visibleQuickHelpField;
        
        private PagingInfoCls paggingInfoField;
        
        /// <remarks/>
        public string InfoMessage {
            get {
                return this.infoMessageField;
            }
            set {
                this.infoMessageField = value;
            }
        }
        
        /// <remarks/>
        public string HtmlContent {
            get {
                return this.htmlContentField;
            }
            set {
                this.htmlContentField = value;
            }
        }
        
        /// <remarks/>
        public string RefKeyId {
            get {
                return this.refKeyIdField;
            }
            set {
                this.refKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public object RetObject {
            get {
                return this.retObjectField;
            }
            set {
                this.retObjectField = value;
            }
        }
        
        /// <remarks/>
        public object RetObject1 {
            get {
                return this.retObject1Field;
            }
            set {
                this.retObject1Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObject2 {
            get {
                return this.retObject2Field;
            }
            set {
                this.retObject2Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObject3 {
            get {
                return this.retObject3Field;
            }
            set {
                this.retObject3Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObject4 {
            get {
                return this.retObject4Field;
            }
            set {
                this.retObject4Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObject5 {
            get {
                return this.retObject5Field;
            }
            set {
                this.retObject5Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObjectExtraParam1 {
            get {
                return this.retObjectExtraParam1Field;
            }
            set {
                this.retObjectExtraParam1Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObjectExtraParam2 {
            get {
                return this.retObjectExtraParam2Field;
            }
            set {
                this.retObjectExtraParam2Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObjectExtraParam3 {
            get {
                return this.retObjectExtraParam3Field;
            }
            set {
                this.retObjectExtraParam3Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObjectExtraParam4 {
            get {
                return this.retObjectExtraParam4Field;
            }
            set {
                this.retObjectExtraParam4Field = value;
            }
        }
        
        /// <remarks/>
        public object RetObjectExtraParam5 {
            get {
                return this.retObjectExtraParam5Field;
            }
            set {
                this.retObjectExtraParam5Field = value;
            }
        }
        
        /// <remarks/>
        public string RetUrl {
            get {
                return this.retUrlField;
            }
            set {
                this.retUrlField = value;
            }
        }
        
        /// <remarks/>
        public string RetUrlTarget {
            get {
                return this.retUrlTargetField;
            }
            set {
                this.retUrlTargetField = value;
            }
        }
        
        /// <remarks/>
        public string RetExtraParam1 {
            get {
                return this.retExtraParam1Field;
            }
            set {
                this.retExtraParam1Field = value;
            }
        }
        
        /// <remarks/>
        public string RetExtraParam2 {
            get {
                return this.retExtraParam2Field;
            }
            set {
                this.retExtraParam2Field = value;
            }
        }
        
        /// <remarks/>
        public string RetExtraParam3 {
            get {
                return this.retExtraParam3Field;
            }
            set {
                this.retExtraParam3Field = value;
            }
        }
        
        /// <remarks/>
        public string RetExtraParam4 {
            get {
                return this.retExtraParam4Field;
            }
            set {
                this.retExtraParam4Field = value;
            }
        }
        
        /// <remarks/>
        public string RetExtraParam5 {
            get {
                return this.retExtraParam5Field;
            }
            set {
                this.retExtraParam5Field = value;
            }
        }
        
        /// <remarks/>
        public string RetExtraParam6 {
            get {
                return this.retExtraParam6Field;
            }
            set {
                this.retExtraParam6Field = value;
            }
        }
        
        /// <remarks/>
        public string SaveFile {
            get {
                return this.saveFileField;
            }
            set {
                this.saveFileField = value;
            }
        }
        
        /// <remarks/>
        public bool Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public bool RetBoolean {
            get {
                return this.retBooleanField;
            }
            set {
                this.retBooleanField = value;
            }
        }
        
        /// <remarks/>
        public int RetNumber {
            get {
                return this.retNumberField;
            }
            set {
                this.retNumberField = value;
            }
        }
        
        /// <remarks/>
        public int RetNumber1 {
            get {
                return this.retNumber1Field;
            }
            set {
                this.retNumber1Field = value;
            }
        }
        
        /// <remarks/>
        public int RetNumber2 {
            get {
                return this.retNumber2Field;
            }
            set {
                this.retNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public int RetNumber3 {
            get {
                return this.retNumber3Field;
            }
            set {
                this.retNumber3Field = value;
            }
        }
        
        /// <remarks/>
        public int RetNumber4 {
            get {
                return this.retNumber4Field;
            }
            set {
                this.retNumber4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal RetNumberDecimal {
            get {
                return this.retNumberDecimalField;
            }
            set {
                this.retNumberDecimalField = value;
            }
        }
        
        /// <remarks/>
        public decimal RetNumberDecimal1 {
            get {
                return this.retNumberDecimal1Field;
            }
            set {
                this.retNumberDecimal1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal RetNumberDecimal2 {
            get {
                return this.retNumberDecimal2Field;
            }
            set {
                this.retNumberDecimal2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal RetNumberDecimal3 {
            get {
                return this.retNumberDecimal3Field;
            }
            set {
                this.retNumberDecimal3Field = value;
            }
        }
        
        /// <remarks/>
        public decimal RetNumberDecimal4 {
            get {
                return this.retNumberDecimal4Field;
            }
            set {
                this.retNumberDecimal4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal RetDecimal {
            get {
                return this.retDecimalField;
            }
            set {
                this.retDecimalField = value;
            }
        }
        
        /// <remarks/>
        public bool IsReturnUrlLink {
            get {
                return this.isReturnUrlLinkField;
            }
            set {
                this.isReturnUrlLinkField = value;
            }
        }
        
        /// <remarks/>
        public string XmlData {
            get {
                return this.xmlDataField;
            }
            set {
                this.xmlDataField = value;
            }
        }
        
        /// <remarks/>
        public string XmlDataSchema {
            get {
                return this.xmlDataSchemaField;
            }
            set {
                this.xmlDataSchemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] RetBytes {
            get {
                return this.retBytesField;
            }
            set {
                this.retBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MediaBytes {
            get {
                return this.mediaBytesField;
            }
            set {
                this.mediaBytesField = value;
            }
        }
        
        /// <remarks/>
        public string FocusControl {
            get {
                return this.focusControlField;
            }
            set {
                this.focusControlField = value;
            }
        }
        
        /// <remarks/>
        public string XmlDataResult {
            get {
                return this.xmlDataResultField;
            }
            set {
                this.xmlDataResultField = value;
            }
        }
        
        /// <remarks/>
        public string XmlDataResultSchema {
            get {
                return this.xmlDataResultSchemaField;
            }
            set {
                this.xmlDataResultSchemaField = value;
            }
        }
        
        /// <remarks/>
        public bool ShowDialogMessage {
            get {
                return this.showDialogMessageField;
            }
            set {
                this.showDialogMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessServiceId {
            get {
                return this.processServiceIdField;
            }
            set {
                this.processServiceIdField = value;
            }
        }
        
        /// <remarks/>
        public string AssetCode {
            get {
                return this.assetCodeField;
            }
            set {
                this.assetCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AssetLevelId {
            get {
                return this.assetLevelIdField;
            }
            set {
                this.assetLevelIdField = value;
            }
        }
        
        /// <remarks/>
        public string FollowUpSubject {
            get {
                return this.followUpSubjectField;
            }
            set {
                this.followUpSubjectField = value;
            }
        }
        
        /// <remarks/>
        public string FollowUpDescription {
            get {
                return this.followUpDescriptionField;
            }
            set {
                this.followUpDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        public string FollowUpStatus {
            get {
                return this.followUpStatusField;
            }
            set {
                this.followUpStatusField = value;
            }
        }
        
        /// <remarks/>
        public string QuickHelp {
            get {
                return this.quickHelpField;
            }
            set {
                this.quickHelpField = value;
            }
        }
        
        /// <remarks/>
        public int VisibleQuickHelp {
            get {
                return this.visibleQuickHelpField;
            }
            set {
                this.visibleQuickHelpField = value;
            }
        }
        
        /// <remarks/>
        public PagingInfoCls PaggingInfo {
            get {
                return this.paggingInfoField;
            }
            set {
                this.paggingInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PageInfoItemCls {
        
        private int pageField;
        
        private string activeField;
        
        private string urlField;
        
        private string pageTextField;
        
        /// <remarks/>
        public int Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string PageText {
            get {
                return this.pageTextField;
            }
            set {
                this.pageTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PagingInfoCls {
        
        private int startIndexField;
        
        private int endIndexField;
        
        private int currentPageIndexField;
        
        private int pageCountField;
        
        private int totalSegmentField;
        
        private int pageSizeField;
        
        private int totalFoundField;
        
        private PageInfoItemCls[] pageInfoItemsField;
        
        /// <remarks/>
        public int StartIndex {
            get {
                return this.startIndexField;
            }
            set {
                this.startIndexField = value;
            }
        }
        
        /// <remarks/>
        public int EndIndex {
            get {
                return this.endIndexField;
            }
            set {
                this.endIndexField = value;
            }
        }
        
        /// <remarks/>
        public int CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalSegment {
            get {
                return this.totalSegmentField;
            }
            set {
                this.totalSegmentField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int TotalFound {
            get {
                return this.totalFoundField;
            }
            set {
                this.totalFoundField = value;
            }
        }
        
        /// <remarks/>
        public PageInfoItemCls[] PageInfoItems {
            get {
                return this.pageInfoItemsField;
            }
            set {
                this.pageInfoItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CheckWsCompletedEventHandler(object sender, CheckWsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckWsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckWsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ProcessComandCompletedEventHandler(object sender, ProcessComandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessComandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessComandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AjaxOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AjaxOut)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591